import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  // TODO Index Page with links to all blogs
  return (
    <div>
      <Head>
        <title>Traveltime Blogs Examples</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
